# Generated by Django 4.0.6 on 2022-07-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsproj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='firstname',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
