# Generated by Django 4.0.6 on 2022-07-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsproj', '0003_batch_courses_account_isstudent_account_isteacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
