# Generated by Django 4.0.6 on 2022-07-12 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsproj', '0004_batch_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
