# Generated by Django 4.0.6 on 2022-07-12 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsproj', '0005_task_createdby_task_date_created_task_isactive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssigningUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeModule', models.CharField(default='n/a', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsproj.batch')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmsproj.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_Object', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_Object', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentAssignedBatch',
        ),
    ]
