# Generated by Django 4.0.6 on 2022-07-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsproj', '0007_tasksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
