# Generated by Django 4.0.6 on 2022-07-13 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsproj', '0008_alter_task_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigninguser',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assign_Course', to='lmsproj.courses'),
        ),
    ]
