# Generated by Django 4.0.6 on 2022-07-13 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsproj', '0009_alter_assigninguser_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigninguser',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigingusertobatch', to='lmsproj.batch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursrealtedtobatch', to='lmsproj.courses'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exambatch', to='lmsproj.batch'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examcourse', to='lmsproj.courses'),
        ),
        migrations.AlterField(
            model_name='task',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskbatch', to='lmsproj.batch'),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskcreateduser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasksubmittedstudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasktobesubmited', to='lmsproj.task'),
        ),
    ]
