# Generated by Django 4.0.6 on 2022-07-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsproj', '0010_alter_assigninguser_batch_alter_batch_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
